# Generated by Django 3.2.8 on 2021-10-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('India', 'India')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
